### ISSUE TITLE
STT0070: Merge meta data with training data.

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt-create_meta#1]
### Description
Merge the latest training data with it's corresponding meta data.

### Completion Criteria
A training data with it's meta data combined in hugging face dataset repo.

### Implementation
1. Create a csv file of additional data data we have since last data collection. 
2. merge the additional dataset we have with the meta data.
3. Concat the old dataset with meta data to the new dataset with meta data.

# Subtask 
- [x] create a script to remove existing file_name in old training data from new training data.
- [x] merge the additional training data we have gained  for each department with it's corresponding meta data.
- [x] update the hugging face stt training data with metadata repo with the details of new dataset we have.
